name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  SYSTEM_URL: http://tdrive.manofuranium.workers.dev/oppppp7tproosystem.zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install -y brotli
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar

       - name: System.img
         run: |
              sudo aria2c $SYSTEM_URL
              sudo unzip *.zip
        
       - name: System.img
         run: |
              sudo mkdir lel
              sudo mount -ro loop system.img lel/
              sudo zip -r op7tapps.zip lel/system/app lel/system/priv-app
              
       - name: upload aonly n infog
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit op7tapps.zip
 
